### ISSUE TITLE
Add NGINX as a reverse proxy + maybe LetsEncrypt?

### ISSUE THREAD

**Issue by johnpyp** [sebgl/htpc-download-box#12]
I think adding nginx as a reverse proxy to all of the apps would be a pretty cool addition. I imagine it working it like this:

- localhost:32400 -> localhost:port/plex
- localhost:8112 -> localhost:port/deluge
- localhost:6789 -> localhost:port/nzbget
...etc

This solves a couple of issues:

1) Solves the issue of forgetting which port is which, mapping them instead to paths on a unified domain.

2) Allows for port-forwarding a single port to be able to access all of the programs in the home server. This would be a really cool addition, because normally you have to port forward every single port individually, and target them individually with a domain if you want to do that too.

Along with NGINX, although this is a less universal issue so it might be reserved for some kind of "advanced" configuration, it could be useful to add LetsEncrypt. What this will let the user do is port forward the single nginx domain and make it all https. I don't know if this would impact any of the apps, or specifically Plex web forwarding.

If supporting public-facing port forwarding is something that is desirable, there would also need to be a section on adding basic auth with nginx to secure it.

**Comment by johnpyp** [comment]
I've done a bit of research here, and there is a really solid image with a GUI to configure it all: https://nginxproxymanager.jc21.com/

It will allow various levels of what I'm referring to:

Level 1) Unifying local networking with subdomains or paths:
- `deluge.localhost`
- `localhost/deluge`

Level 2) Port forwarding a single port with basic auth to access all of your apps remotely.

Level 3) Point a domain at your ip, optionally protected by cloudflare, and encrypt the secure the entire thing with https via LetsEncrypt.

nginxproxymanager covers all of these cases painlessly, without the user needing to do any manual configuration. It handles the reverse proxying, authentication and letsencrypt certificates.

**Comment by sebgl** [comment]
> I think adding nginx as a reverse proxy to all of the apps would be a pretty cool addition

Yeah sounds like a good idea to ease the user access!

> it could be useful to add LetsEncrypt

I think NGINX + basic auth + TLS would make sense if you access this outside your local network, indeed 👍 

> there is a really solid image with a GUI to configure it all: https://nginxproxymanager.jc21.com/

What I don't like much with this is the extra dependency to a database container that we also need to spawn.
I think there are other alternatives that can act as proxy + TLS termination, with a UI for discoverability. For instance: [traefik](https://traefik.io/). It does discover other containers from labels applied to them directly, does not require any particular configuration file to discover those, and not extra database.
It also handles Let's encrypt.

Another project worth looking at: [organizr](https://github.com/causefx/Organizr). It acts as a front-end web UI to "embed" access other services.

Maybe (NGINX|traefik) with basic auth and let's encrypt + organizr could make sense here? (I think we should aim for the most minimal setup that makes sense)

**Comment by johnpyp** [comment]
Yeah, I was just looking at traefik a few minutes ago. It seems like a really cool solid project too. I'll test it out today.

**Comment by johnpyp** [comment]
I tried organizr once. It froze on me and was a bit glitchy. I'll try it again as well. Organizr does require a reverse proxy anyway to embed the other services I believe.

**Comment by johnpyp** [comment]
I've done some testing with traefik, and I was kind of able to make it work. I'm confident it has the capability to do what we want here.

The issue however, is that the configuration for traefik is fairly complex for anyone not willing to spend a long time troubleshooting and playing around with different settings to get the setup that they want. Given that not everyone would want to necessarily port-forward their setup, traefik doesn't allow for much variation. It is worth mentioning as well that traefik does require configuration files to set it up with LetsEncrypt. The dashboard is also just a monitoring dashboard I believe, it doesn't really do anything.

nginx-proxy-manager also has a couple downsides like you mentioned: 1) requires a mysql/mariadb instance. This is my setup right now: https://pastebin.com/NnPL07yH. 2) It requires you to make a configuration file, though it isn't complicated at all. 3) Documentation is little to none. This is the bigger sticking point for me, but the actual program is extremely intuitive, and I was able to figure out all of what I was looking for by playing around with it.

The biggest benefit of nginx-proxy-manager in my mind is that it frames the reverse proxy in a way that is very simple to understand, and even simpler to edit, without any kind of advanced knowledge. The interface is It has abstractions like authentication profiles where you can define multiple users that are allowed to access a particular service with basic auth. Importantly, the proxy manager allows easy configuration for multiple different sets of use cases. If you just want to organize your apps locally and expose them as subdomains for organization, you can do that. If you want to expose it without HTTPS, you can do that too. And if you want to include https, it is an extremely painless process to add that as well. Being able to support multiple use cases in this way seems really good.

**Comment by johnpyp** [comment]
After more testing, I was able to figure out a workaround to the configuration file requirement, allowing to operate with pretty much no friction to the user, just a few fields in the .env file.

This puts traefik as a clear winner, as it has the least required user interaction, and removing https or making it all local should be an easy step for users who want to do that.

I'll make a PR tonight :+1:

**Comment by johnpyp** [comment]
Traefik added in https://github.com/sebgl/htpc-download-box/pull/17 :+1:
