### ISSUE TITLE
Add a filebrowser

### ISSUE THREAD

**Issue by johnpyp** [sebgl/htpc-download-box#15]
Since we want to support things like remote access to your services, adding a web-based filebrowser would compliment that really nicely. It can be pointed at the centralized ROOT folder and allow the user to have pretty much full control over their setup other than full terminal access.

A quick search gives this, and it looks like a decent option: https://filebrowser.xyz/

Edit: Actually, it seems like it supports limited terminal access too!

**Comment by sebgl** [comment]
What would be the main use case for a file browser? (I never really felt it was missing)

**Comment by johnpyp** [comment]
It probably is pretty niche, but I can imagine a use case where someone is controlling their setup completely remotely and they need to rename or fix something in their file setup.

Since it probably adds more bloat than usefullness for the average person, it might be better to add this into a new "optional additions" section of the docs. We can have a list of niche programs and a basic description for people to build off of if they want to manually edit their docker-compose file.
