### ISSUE TITLE
ERROR: for deluge  Cannot start service deluge: 

### ISSUE THREAD

**Issue by nagydavid** [sebgl/htpc-download-box#25]
Hey,

First of all thank you for this walk-through. I am almost there, however I encountered an error which I don't know how to fix. (I am a newbie in docker).
I basically followed all instruction regarding docker/or your github. Allthough I cannot figure out but my deluge container keep failing to set up.

I think it is due to the `network_mode: service:vpn # run on the vpn network`, because if I change it to `host` it starts up normally, but then I have no vpn.

Thanks for help in advance

**Comment by jbusuttil83** [comment]
but do you want to use a vpn ? in my case I am not using a vpn so I removed the VPN service from the docker compose and changed network_mode to host. That way the deluge web ui would also be accesible on my internal network.

**Comment by sebgl** [comment]
Indeed, the VPN container is only useful if you have subscribed to (or are running your own) VPN service.
Otherwise you should disable the VPN container altogether.
