### ISSUE TITLE
Sonarr/Radarr/Jackett Behind VPN

### ISSUE THREAD

**Issue by y0da822** [sebgl/htpc-download-box#32]
Think its a good idea to have Sonarr/Radarr/Jackett behind vpn?

Was thinking of setting it that way since the infrastructure is already there...

**Comment by jbusuttil83** [comment]
Yes it is if in your country the downloads are monitored.

**Comment by sebgl** [comment]
You probably mostly want the software that does the download behind a VPN (eg. Deluge), but indeed it is definitely ok to also put Sonarr/Radarr/Jackett behind the VPN.
