### ISSUE TITLE
Question: why not all download apps +VPN in 1 docker?

### ISSUE THREAD

**Issue by zilexa** [sebgl/htpc-download-box#33]
I have been searching for a solution like yours: download apps (r(u)torrent, sonarr, radarr, nzbget) in 1 docker together with OpenVPN. Simply to have them only work via VPN and isolate them from the rest of the system.
Your solution however creates a docker for each app! Why? Isn't it much easier to create 1 docker image with all of them?

And a seperate docker for the playback solution/database like Plex Server?

This is just an honest question. It seems like a lot more work to do it your way, but I am definitely a noob when it comes to Docker and novice when it comes to Linux (just switched from Win10/MacOS to Ubuntu Budgie). 

2nd question: Sonarr/Radarr will visit torrent sites, I would want them behind the VPN just like Deluge. In your stack, you clearly allow them to access the internet without VPN.. Why put Deluge behind it but not these two?

**Comment by sebgl** [comment]
1) This is generally considered good practice to keep one container per app. It makes the whole system more flexible imo.
2) It's up to you, I don't care much about visiting torrent websites. But it totally makes sense for you to also put them on the VPN network if you think it's better :)

**Comment by jbusuttil83** [comment]
I agree with @sebgl , it is more flexible like this even more for people who want to tweak the setup.

**Comment by zilexa** [comment]
Thanks! Those are enough arguments for me.
