### ISSUE TITLE
Not able to access deluge WebUI from network

### ISSUE THREAD

**Issue by Daemonslayer2048** [sebgl/htpc-download-box#34]
I have essentially used the docker-compose example provided but I can not access the deluge WebUI from the network. However from the docker host I can curl 127.0.0.1:8112 and the deluge WebUI responds. Not I did change the vpn -r command to my internal network of 10.0.10./24. 
For testing I took the firewall on the host down, so that should take care of that issue. 
Any ideas?

**Comment by jbusuttil83** [comment]
did you try to access it without vpn ?
