### ISSUE TITLE
i686 support?

### ISSUE THREAD

**Issue by ssv-w32** [sebgl/htpc-download-box#5]
Hello there!

First of all thanks a lot for this project!

I've tried to run it on my laptop with _i686_ and _Ubuntu 16.04.5 LTS_ on board but got the following errors for all the images:
```
Recreating plex-server ... done
Recreating radarr      ... done
Recreating nzbget      ... done
Recreating sonarr      ... done
Recreating jackett     ... done
Recreating deluge      ... done
Attaching to plex-server, jackett, sonarr, nzbget, docker-compose_deluge_1, radarr
plex-server    | standard_init_linux.go:178: exec user process caused "exec format error"
jackett        | standard_init_linux.go:178: exec user process caused "exec format error"
nzbget         | standard_init_linux.go:178: exec user process caused "exec format error"
deluge_1       | standard_init_linux.go:178: exec user process caused "exec format error"
sonarr         | standard_init_linux.go:178: exec user process caused "exec format error"
radarr         | standard_init_linux.go:178: exec user process caused "exec format error"
jackett exited with code 1
nzbget exited with code 1
radarr exited with code 1
sonarr exited with code 1
```

Do you know if there is any way to run these images on this particular configuration without issues?

Thanks in advance!

**Comment by sebgl** [comment]
HI @ssv-w32 ! Sorry I cannot help you much with your question.
Looks like there are some incompatibilities with the Docker images and the fact you're running on i686 (32 bits)?

**Comment by ssv-w32** [comment]
@sebgl, yup, this is x32 and for now I see no reason why it should not work, since it should support x32. anyway there is always and option to setup stack without docker, so should be fine but will take more time :)
