### ISSUE TITLE
Option for transmission daemon instead of deluge

### ISSUE THREAD

**Issue by duindain** [sebgl/htpc-download-box#53]
I'm just about to start using this project as I currently have all these items installed directly on my main linux pc but I have to add NzbGet and I didn't want to increase the issues mainly with the split tunneling config which kindof messes up any complex networking on the host pc anyway so i was looking for VM alternatives or docker

I've looked up a few comparisons and it seems transmission is the better choice for lightweight feature rich torrent client compared to deluge though they are very similar 

Is there an option to use transmission instead of deluge?

I originally found the project from a search that hit this pi fork first https://github.com/marchah/pi-htpc-download-box
and they have swapped to transmission from deluge so I was going to try the config from there for that part and see if i could get it working as the daemon option is very lightweight and its what i already have working now with high thousands of files with no issues for years

**Comment by jbusuttil83** [comment]
You should be able to work with transmission as well.

**Comment by duindain** [comment]
ty
