### ISSUE TITLE
Needing some over all help with ths setup

### ISSUE THREAD

**Issue by raksasas** [sebgl/htpc-download-box#6]
Where do I begin...  First off, thank you for this write up.  This is my first time using docker.  I was able to get everything installed following this guide as far as I can tell.  (Skipped Plex part, not really intrested in Plex at the moment.)  I feel like there was a few things skipped over in it but I believe I was able to connect some dots and get everything installed with a few small changes here and there.  As for everything working togeather that is where I am at. It doesn't seem to be working togeather.  I can pull up everthing via the URl:port but nothing seems to be talking to eather other.  So If you don't mine helping work throught this it would be helpful and a learning experiance.

So they system. It is a VM running Debina 9 (netinstall) with: Docker version 18.09.2, build 6247962, docker-compose version 1.24.0-rc1, build 0f3d4dda.

If we can lets please start with the VPN then move to deluge, jacket, sonarr,radarr, and so forth,

First the VPN: (PIA)
- My First question is more of a concern... You talk about it but don't give any directions on it in the iptables section. How do I make sure that everything halts if the vpn connection drops?  Are the iptables already in place inside the container?  Refering to the safety featuers you talk about.  I belive 3 is working but there is not mention of how to setup the first 2 which is why i am wondering if they are already setup in the docker-compose container.
- Looking at the "docker logs vpn" I have the following: The "Warning" and a repeating "Authenticate/Decrypt" (Got the command from one of the other issue posts)

> Sat Feb 23 15:09:20 2019 WARNING: file '/vpn/vpn.auth' is group or others accessible
Sat Feb 23 15:09:20 2019 OpenVPN 2.4.6 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Jul  8 2018
Sat Feb 23 15:09:20 2019 library versions: LibreSSL 2.7.4, LZO 2.10
Sat Feb 23 15:09:20 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]46.166.137.237:1198
Sat Feb 23 15:09:20 2019 UDP link local: (not bound)
Sat Feb 23 15:09:20 2019 UDP link remote: [AF_INET]46.166.137.237:1198
Sat Feb 23 15:09:20 2019 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Sat Feb 23 15:09:21 2019 [8cf34dba64052ef93bb53a1be95d0753] Peer Connection Initiated with [AF_INET]46.166.137.237:1198
Sat Feb 23 15:09:22 2019 TUN/TAP device tun0 opened
Sat Feb 23 15:09:22 2019 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Sat Feb 23 15:09:22 2019 /sbin/ip link set dev tun0 up mtu 1500
Sat Feb 23 15:09:22 2019 /sbin/ip addr add dev tun0 local 10.8.10.6 peer 10.8.10.5
Sat Feb 23 15:09:22 2019 Initialization Sequence Completed
Sat Feb 23 15:16:04 2019 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #1223 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sat Feb 23 15:16:07 2019 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #2413 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sat Feb 23 15:16:08 2019 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #2716 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sat Feb 23 15:09:20 2019 WARNING: file '/vpn/vpn.auth' is group or others accessible
Sat Feb 23 15:09:20 2019 OpenVPN 2.4.6 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Jul  8 2018
Sat Feb 23 15:09:20 2019 library versions: LibreSSL 2.7.4, LZO 2.10
Sat Feb 23 15:09:20 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]46.166.137.237:1198
Sat Feb 23 15:09:20 2019 UDP link local: (not bound)
Sat Feb 23 15:09:20 2019 UDP link remote: [AF_INET]46.166.137.237:1198
Sat Feb 23 15:09:20 2019 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Sat Feb 23 15:09:21 2019 [8cf34dba64052ef93bb53a1be95d0753] Peer Connection Initiated with [AF_INET]46.166.137.237:1198
Sat Feb 23 15:09:22 2019 TUN/TAP device tun0 opened
Sat Feb 23 15:09:22 2019 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Sat Feb 23 15:09:22 2019 /sbin/ip link set dev tun0 up mtu 1500
Sat Feb 23 15:09:22 2019 /sbin/ip addr add dev tun0 local 10.8.10.6 peer 10.8.10.5
Sat Feb 23 15:09:22 2019 Initialization Sequence Completed
Sat Feb 23 15:16:04 2019 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #1223 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sat Feb 23 15:16:07 2019 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #2413 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Sat Feb 23 15:16:08 2019 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #2716 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings

**Comment by raksasas** [comment]
- I have gotten the Warning message to go away by adding "auth-nocache" to the .ovpn config file
- "Authenticate/Decrypt packet error" - used the "mute-replay-warnings" in the .ovpn config file because it apears th there are several factors that cause this
 -  that just leaves the safety features concern.

I am not sure if it matters but the vpn micro services shows unhealthy
> e988f366f1ef        dperson/openvpn-client:latest   "/sbin/tini -- /usr/…"   6 minutes ago       Up 6 minutes (unhealthy)   0.0.0.0:8112->8112/tcp   vpn

**Comment by raksasas** [comment]
VPN - Resolved I believe.

I have gotten the vpn container stations to be "healthy".

> 5f81cbe6ba35        dperson/openvpn-client:latest   "/sbin/tini -- /usr/…"   23 minutes ago      Up 23 minutes (healthy)   0.0.0.0:8112->8112/tcp   vpn

To get that and get hostnames to resolve I had to add a "dns" section to the vpn section of the .yml file

`      - net_admin # required to modify network interfaces
    dns:
      - 1.1.1.1
      - 8.8.8.8
    restart: unless-stopped`

After doing that the container showed "healthy" and I could resolve host names inside the "vpn" and "deluge" containers  

`curl ipinfo.io/ip`

I am stll a little concern on verify if the vpn connection will leak if the vpn is disconnected but I don't know how to check that.

**Comment by raksasas** [comment]
Deluge

It appears that I may be having the same issues as this guy:
https://github.com/sebgl/htpc-download-box/issues/4

But i am still in the process of checking.  I have the same downloads going on 2 systesm this "hds" (htpc downlaod system) and another system that I normally use (Trasmission). I'll just say that it apears the other system is winning as this new setup deluge hasn't even got anyting download yet. Nothing is even in the "incomplete" folder. I click on the times in deluge I see a status of "Error: Connection times out"

Another problem is that if I place a file in the "torrent-blackhole" folder Deluge doesn't seem to be picking it up.  I have indeed double checked that the autoadd is checked and pointing to the correct directory.

**Comment by sebgl** [comment]
Hey @raksasas! Let's try to solve your issues!

> I am stll a little concern on verify if the vpn connection will leak if the vpn is disconnected but I don't know how to check that.

To check that the VPN ip address is used for downloading torrents (and not your own), you can try the TorGuard method I explained there: https://github.com/sebgl/htpc-download-box/blob/master/README.md#docker-container-1

Then you could simulate the VPN going down by killing the VPN docker container and see how it goes on Deluge side. Or maybe regenerate your VPN password and verify that Deluge cannot download anything anymore with the old password (vpn connection should drop at some point since you'd still be using the old password).
But to check that you first need to get Deluge working 😄.

> Another problem is that if I place a file in the "torrent-blackhole" folder Deluge doesn't seem to be picking it up.

Is it correctly pointing to a directory in a volume mounted into your Docker container? Can you share what you have in the `docker-compose.yml` vs. the Deluge configuration?

> When I clicked on the items in deluge I see a status of "Error: Connection times out"

Are you able to reach internet from the Deluge container? (you could run something like `docker exec -ti deluge curl google.com` or any other website). Also maybe try with a torrent that has a lot of sources to make sure the issue does not come from a problem with the torrent itself.

**Comment by raksasas** [comment]
In no paritulary order

I havn't had an issue with TorGuard it worked even before I added the DNS to the yml file
![screenshot_2019-02-25_18-14-12](https://user-images.githubusercontent.com/11538963/53378413-1928ec00-392b-11e9-8f4e-81c462571565.png)

Here is the yml file and deluge download setup.  I have the other services commented out at the moment.
![screenshot_2019-02-25_18-30-48](https://user-images.githubusercontent.com/11538963/53378542-948a9d80-392b-11e9-8550-83f0c21b1138.png)

```
tds-admin@tds:~$ cd tds-services/
tds-admin@tds:~/tds-services$ cat docker-compose.yml 
version: '3.7'
services:

  vpn:
    container_name: vpn
    image: dperson/openvpn-client:latest
    cap_add:
      - net_admin # required to modify network interfaces
    dns:
      - 1.1.1.1
      - 8.8.8.8
    restart: unless-stopped
    volumes:
      - /dev/net/tun:/dev/net/tun # tun device
      - ${HOME}/.config/vpn:/vpn # OpenVPN configuration
    ports:
      - 8112:8112 # port for deluge web UI to be reachable from local network
    command: '-r 192.168.138.0/24' # route local network traffic

  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: always
    network_mode: service:vpn # run on the vpn network
    environment:
      - PUID=1000 # default user id, for downloaded files access rights
      - PGID=1000 # default group id, for downloaded files access rights
      - TZ=Europe/Paris # timezone
    volumes:
      - ${HOME}/downloads:/downloads # download folder
      - ${HOME}/.config/deluge:/config # config files

#  jackett:
#    container_name: jackett
#    image: linuxserver/jackett:latest
#    restart: unless-stopped
#    network_mode: host
```

Here is my "downloads"  folder...  mounted share. I use my NAS (nfs)for storage so I mounted it into the system to hold the downloads.  I do not suspect that this may be a problem.  I am going to test this by removing the the mounted share.  
```
tds-admin@tds:~/tds-services$ ls -lah ~/downloads
total 162K
drwxr-xr-x 11 nobody    nogroup     12 Feb 18 11:11 .
drwxr-xr-x  6 tds-admin tds-admin 4.0K Feb 17 10:45 ..
drwxr-xr-x  2 nobody    nogroup      2 Feb 18 14:40 complete
drwxr-xr-x  2 nobody    nogroup      2 Feb 18 09:56 incomplete
drwxr-xr-x  2 nobody    nogroup      2 Feb 18 12:25 movies
drwxr-xr-x  2 nobody    nogroup      2 Feb 17 11:36 nzb
-rw-r--r--  1 nobody    nogroup   527K Feb 24 12:51 nzbget.log
drwxr-xr-x  2 nobody    nogroup      2 Feb 17 10:52 ongoing
drwxr-xr-x  2 nobody    nogroup      6 Feb 18 09:57 queue
drwxr-xr-x  2 nobody    nogroup      2 Feb 18 10:58 series
drwxr-xr-x  2 nobody    nogroup      2 Feb 18 09:57 tmp
drwxr-xr-x  2 nobody    nogroup      3 Feb 18 15:06 torrent-blackhole

```

I have inded verified that the Deluge and VPN containers can both get to the inter net. But again I had to add the DNS to the yml file for them to resolve hostnames.
```
Last login: Sun Feb 24 15:05:43 2019 from 192.168.138.17
tds-admin@tds:~$ docker exec -ti vpn bash
bash-4.4# curl google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
bash-4.4# curl ipinfo.io/ip
212.92.112.141
bash-4.4# exit
exit
tds-admin@tds:~$ docker exec -ti deluge bash
root@cbbf1b8e8fe6:/# curl google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
root@cbbf1b8e8fe6:/# curl ipinfo.io/ip
212.92.112.141
root@cbbf1b8e8fe6:/# exit
exit

```

So I also tried to use a the debian iso torrent and Deluge isn't download anyting the hours/days just keeps growing. This is diffrent then the others "Tracker Status:    debian.org: Announce OK'  The downlaod has been running for at least 30 minutes now and it is still at 0.00%. The link I used
[https://cdimage.debian.org/debian-cd/current/amd64/bt-cd/debian-9.8.0-amd64-xfce-CD-1.iso.torrent](url)

I think that covered everything. As I stated above I am going to remove the network share and see if that makes a diffrence in the downloading.

**Comment by raksasas** [comment]
It does't appear to make a diffrence standard folder vs a network share.

**Comment by raksasas** [comment]
I belive I have verified that Deluge" can read/write/execute inside it's container

```
tds-admin@tds:~/tds-services$ docker exec -ti deluge bash
root@042a55a27a75:/# ls downloads
complete  incomplete  movies  nzb  nzbget.log  ongoing  queue  series  tmp  torrent-blackhole
root@042a55a27a75:/# mkdir downloads/test123
root@042a55a27a75:/# ls downloads
complete  incomplete  movies  nzb  nzbget.log  ongoing  queue  series  test123  tmp  torrent-blackhole
root@042a55a27a75:/# mkdir downloads/incomplete/test123
root@042a55a27a75:/# ls downloads/incomplete/
test123
root@042a55a27a75:/# touch downloads/incomplete/testfile
root@042a55a27a75:/# mkdir downloads/incomplete/test123
mkdir: cannot create directory ‘downloads/incomplete/test123’: File exists
root@042a55a27a75:/# ls downloads/incomplete/
test123  testfile
root@042a55a27a75:/# ls -lha downloads/incomplete/
total 18K
drwxr-xr-x  3 nobody nogroup  4 Feb 26 14:04 .
drwxr-xr-x 12 nobody nogroup 13 Feb 26 14:03 ..
drwxr-xr-x  2 nobody nogroup  2 Feb 26 14:03 test123
-rw-r--r--  1 nobody nogroup  0 Feb 26 14:04 testfile
root@042a55a27a75:/# echo 'this is a test' >> downloads/incomplete/testfile
root@042a55a27a75:/# cat downloads/incomplete/testfile
this is a test
root@042a55a27a75:/# 
```

**Comment by raksasas** [comment]
Update:

After a week or so of messing with Deluge with no luck. I decided to stand up another vm  with deluge only, then followed by adding the vpn.  I have done this now with very little changes to the setup you provided.  Deluge is working fine on this test vm.  It downloads, it pulled from from the blackhole folder also.  So I am going to rebuild my tds system and work each service out testing each one from a fresh load and if all goes well i will have a working system. I have speculation that somethin is up with the permissions of the folders but I have done so many change it is just easier to rebuild it.  I'll let you know how it goes.  I probably won't get that done until this coming weekend

**Comment by raksasas** [comment]
Update:

I'm pretty frustrated with this..  I have setup and torn down about a dozen VM's trying to get Deluge working. Trying it this way, trying it that way. I have only manage to get it to work one time on a test vm I discribed in the prior post.  At this point the only two things that are diffrent that I can think of is the test system is 7 ip's away(.60) from the ip I want to use(.53) and the hostname.  
I have tried a VM with LVM vs. non LVM.  Installed older Deluge containter then changing it to the latest. Diffrent volumes for the downloads.  I even used the same copy of the docker-compose.yml form the workings. I tried several diffrent volume locations on the test vm and they all worked...

I am just stumped on it. I have no clue what I did diffrent on the test VM which made it worked. I am temped to just use the test vm I build and move forward.  It doesn't have the hostname and IP I want to use but oh well... /shrug

**Comment by sebgl** [comment]
Sorry to hear that @raksasas, sounds like a small diff hidden somewhere that is hard to spot, probably in deluge config, vpn config, or the volumes and network links between them.

If you think Deluge seems to be the issue, maybe you could try with a different torrent client like [Transmission](https://hub.docker.com/r/linuxserver/transmission/)? I guess it should also work with a pretty similar setup (shared volume for downloaded files, and use the vpn container network).
